Hw04 auth
Irinka1010/nodejs-homework-rest-api pull request #3
Opened 2022-12-21 19:33 UTC by Irinka1010

2022-12-22 19:22 UTC, BohdanGres requested changes
загалом все добре, треба навісити перевірку авторизації на всі старі роути + пару дрібних зауважень

2022-12-22 19:22 UTC, BohdanGres commented on app.js
>  app.use('/api/contacts', contactsRouter);
можеш на весь роут навісити мідлварку авторизаційну

2022-12-22 19:22 UTC, BohdanGres commented on middlewares/auth.js
> +    if (!user || !user.token) {
забула перевірити user.token === token

2022-12-22 20:40 UTC, Irinka1010 commented on middlewares/auth.js
> +    if (!user || !user.token) {
Виправлено

2022-12-22 20:44 UTC, Irinka1010 commented on app.js
>  app.use('/api/contacts', contactsRouter);
Готово. Але я все таки навісила мідлварку в эндпоинтах. Щоб app ненагружати такою інформацією.

2022-12-23 07:47 UTC, BohdanGres approved these changes

2022-12-23 12:34 UTC, merged