Hw06 email
Irinka1010/nodejs-homework-rest-api pull request #5
Opened 2023-01-10 13:53 UTC by Irinka1010

Роботу зроблено. Прошу перевірити. Дякую.

2023-01-11 07:22 UTC, BohdanGres requested changes
все добре, я раджу побільше з докером попрацювати
спробуйте докер компоуз написати з можливістю розробки коду який працює в контейнеру + там де підняти монго локальну

2023-01-11 07:22 UTC, BohdanGres commented on Dockerfile
> +CMD ["npm","run","start",":","dev"]
тут або треба викликати npm run start або маунтити код що б зміни локальні підтягувались у контейнер інакше дев вам нічого не дасть так як код в контейнеру і локальний будуть незалежні

2023-01-12 16:18 UTC, Irinka1010 commented on Dockerfile
> +CMD ["npm","run","start",":","dev"]
Виправлено

2023-01-13 07:21 UTC, BohdanGres commented on docker-compose.yml
> +  node:
ви маєте використовувати свій докерфайл і мені здається що через цей докер-компоуз у вас не буде працювати апі, якщо хочете то можете ще порозбиратись це не є обов`язковим

2023-01-14 20:23 UTC, Irinka1010 commented on docker-compose.yml
> +  node:
Дуже прошу глянути в останнє. Все запускається і працює. Можливо я чогось не бачу. Дякую

2023-01-14 21:06 UTC, BohdanGres commented on docker-compose.yml
> +  node:
Та ви праві це я не догледів
зазвичай ліпше прямо вказувати шлях до докерфайлу але ваш варіант теж робочій
build:
      dockerfile: pathToDockerfile

2023-01-14 21:16 UTC, BohdanGres approved these changes

2023-01-14 21:22 UTC, merged